In [ ]:
import numpy as np

arr= np.array([1,2,3])

print(arr+10)

#[1,2,3]+[10,10,10]
#Broadcasting- No need to perform operation on separate elements

[11 12 13]


In [7]:
arr1= np.array([[1,2,3],[4,5,6]])
print(arr1.ndim)
print(arr1.shape)

2
(2, 3)


In [ ]:
print(type(arr))

#nd-> ndimensional array

<class 'numpy.ndarray'>


In [10]:
print(arr.ndim)
print(arr.shape) #For 1-d it tell no. of elemnts
print(arr.size)
print(arr.dtype)


1
(3,)
3
int64


In [11]:
marks =(10, 20, 30, 40)
print(type(marks))

<class 'tuple'>


In [13]:
arr3= np.array(marks)
print(type(arr3))

<class 'numpy.ndarray'>


In [19]:
zero_arr= np.zeros(6)
print(zero_arr.dtype)
print(zero_arr)

zero_arr= zero_arr.astype(int)
print(zero_arr.dtype)
print(zero_arr)

float64
[0. 0. 0. 0. 0. 0.]
int64
[0 0 0 0 0 0]


In [23]:
ones_arr= np.ones((8,3))
ones_arr=ones_arr.astype(int)
print(ones_arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [32]:
garbage_arr=np.empty(8)
print(garbage_arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#rand()
arr1= np.random.rand(5) #b/w 0 and 1
print(arr1)

[0.42862147 0.75402121 0.22719885 0.25016526 0.43889353]


In [ ]:
#randint()
arr2= np.random.randint(5,50,9)
print(arr2)

[36 42 49 45  7 45 25 35 29]


In [52]:
#randn()
arr3= np.random.randn(5)
print(arr3)

[-2.08527256  0.86274387  1.08786413  0.26247679 -0.67596015]


In [ ]:
#array slicing
arr4= [1,2,3,4,5,6]
print(arr4[1:5])
print(arr4[1:])
print(arr4[:])
print(arr4[:5])

[2, 3, 4, 5]
[2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]


In [90]:
mat= np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(mat[1][0:2])



[4 5]


In [91]:
print(mat[1:,1:])

[[5 6]
 [8 9]]


In [92]:
arr5= np.array([1,2,3,4,5])
print(arr5[::-1])

[5 4 3 2 1]


In [104]:
#reshaping and flatenning
arr6= np.array([1,2,3,4,5,6])
print(arr6.reshape(2,3))
print(arr6.reshape(2,-1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr7= np.array([[1 ,2 ,3],[4 ,5 ,6]])
print(arr6.flatten())

[1 2 3 4 5 6]


In [ ]:
#Shallow copy
arr8=arr6.ravel()
print(arr8)
arr8[0]=10
print(arr8)
print(arr6)



[1 2 3 4 5 6]
[10  2  3  4  5  6]
[[10  2  3]
 [ 4  5  6]]


In [114]:
#Deep copy
arr8=arr6.flatten()
print(arr8)
arr8[0]=8
print(arr8)
print(arr6)

[10  2  3  4  5  6]
[8 2 3 4 5 6]
[[10  2  3]
 [ 4  5  6]]


In [121]:
#Fancy Indexing
arr9=np.array([100,200,300,400])
print(arr9[[1,2]])

[200 300]


In [126]:
#Conditionals
arr10=np.array([10,3,78,50,20,19,4,7,12])
marks=arr10>10
print(marks)
print(arr10[marks])

[False False  True  True  True  True False False  True]
[78 50 20 19 12]


In [136]:
mat4 = np.array ([[1,2,3,4,5], [6,7,8,9, 10]])
print(mat4[ (mat4>4) & (mat4<=8) ])

[5 6 7 8]


In [135]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
y= np.array([
    [7,8,3],
    [2,0,4]
])
print(np.sum(y, axis=0))
print(np.sum(y, axis=1))
print(np.sum(y))
print(np.mean(y))
print(np.median(y))
print(np.max(y)) 
print(np.min(y)) 
print(np.max(y, axis=0))
print(np.max(y, axis=1))
print(np.min(y, axis=0)) 
print(np.min(y, axis=1))

[9 8 7]
[18  6]
24
4.0
3.5
8
0
[7 8 4]
[8 4]
[2 0 3]
[3 0]
